changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: 기능 및 개선
      labels:
        - enhancement
    - title: 버그 수정
      labels:
        - bug
    - title: 문서
      labels:
        - documentation
    - title: 기타 변경
      labels:
        - "*"
