import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { build } from 'esbuild';

const outputDirectory = resolve('supabase/functions/_shared/generated');
await mkdir(outputDirectory, { recursive: true });
await build({
  entryPoints: [resolve('packages/source-adapters/src/astree/edge-entry.ts')],
  outfile: resolve(outputDirectory, 'astree-parser.js'),
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  minify: true,
  treeShaking: true,
  banner: { js: '// GENERATED by pnpm edge:sync. Do not edit manually.' },
});
